version: '3.8'

services:
  db:
    image: mysql:8
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck: # MySQL 초기화 검사 추가
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  flyway:
    image: flyway/flyway:11.0.0
    container_name: flyway-migration
    depends_on: # MySQL 초기화 후 Flyway 실행
      db:
        condition: service_healthy
    environment:
      FLYWAY_URL: ${SPRING_DATASOURCE_URL}
      FLYWAY_USER: ${SPRING_DATASOURCE_USERNAME}
      FLYWAY_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    volumes:
      - ./src/main/resources/db/migration:/flyway/sql
    command: migrate

  backend:
    build:
      context: .
    container_name: spring-boot-app
    env_file: .env
    ports:
      - "8080:8080"
    depends_on: # Flyway 마이그레이션 후 실행
      - db
      - flyway

volumes:
  db_data:

networks:
  default:
    name: techeer-network #