version: '3.8'

services:
  db:
    image: mysql:8
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  flyway:
    image: flyway/flyway:9.22.0
    depends_on:
      - db
    environment:
      FLYWAY_URL: ${SPRING_DATASOURCE_URL}
      FLYWAY_USER: ${SPRING_DATASOURCE_USERNAME}
      FLYWAY_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    volumes:
      - ./src/main/resources/db/migration:/flyway/sql
    command: migrate

  backend:
    build:
      context: .
    container_name: spring-boot-app
    env_file: .env
    ports:
      - "8080:8080"
    depends_on:
      - db
      - flyway

volumes:
  db_data:
