version: '3.8'

services:
  db:
    image: mysql:8
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  flyway:
    image: flyway/flyway:11.0.0
    container_name: flyway-migration
    depends_on:
      db:
        condition: service_healthy
    environment:
      FLYWAY_URL: ${SPRING_DATASOURCE_URL}
      FLYWAY_USER: ${SPRING_DATASOURCE_USERNAME}
      FLYWAY_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    volumes:
      - ./src/main/resources/db/migration:/flyway/sql
    command: migrate

  backend:
    build:
      context: .
    container_name: spring-boot-app
    env_file: .env
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
      flyway:
        condition: service_completed_successfully
    environment:
      - SPRING_SERVLET_MULTIPART_ENABLED=true
      - SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE=1000MB
      - SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE=1000MB
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5

  k6:
    image: grafana/k6
    container_name: k6-load-test
    volumes:
      - ./k6-test.js:/k6-test.js
    command: ["run", "/k6-test.js"]
    depends_on:
      backend:
        condition: service_healthy

volumes:
  db_data:

networks:
  default:
    name: techeer-network
